# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:14:40+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, RootModel, confloat, conint


class OrderStatus(Enum):
    Active = 'Active'
    Cancelled = 'Cancelled'
    Completed = 'Completed'


class OrderHeader(BaseModel):
    id: UUID
    numberOfLineItems: conint(ge=0)
    orderNumber: str
    orderStatus: OrderStatus


class OrderLineItemStatus(Enum):
    Cancelled = 'Cancelled'
    Completed = 'Completed'
    Confirmed = 'Confirmed'
    Pending = 'Pending'
    ProductionCompleted = 'ProductionCompleted'
    ShipmentCompleted = 'ShipmentCompleted'


class QuantityContext(Enum):
    Confirmed = 'Confirmed'
    Invoiced = 'Invoiced'
    Ordered = 'Ordered'
    Produced = 'Produced'
    Shipped = 'Shipped'


class QuantityType(Enum):
    Area = 'Area'
    Count = 'Count'
    GrossWeight = 'GrossWeight'
    Length = 'Length'
    NetNetWeight = 'NetNetWeight'
    NetWeight = 'NetWeight'
    NominalWeight = 'NominalWeight'
    TareWeight = 'TareWeight'


class QuantityUOM(Enum):
    Bale = 'Bale'
    Box = 'Box'
    Centimeter = 'Centimeter'
    Decimeter = 'Decimeter'
    Foot = 'Foot'
    Gram = 'Gram'
    HundredPounds = 'HundredPounds'
    Inch = 'Inch'
    Kilogram = 'Kilogram'
    Kilometer = 'Kilometer'
    Meter = 'Meter'
    MetricTon = 'MetricTon'
    Millimeter = 'Millimeter'
    Package = 'Package'
    PalletUnit = 'PalletUnit'
    Piece = 'Piece'
    Pound = 'Pound'
    PulpUnit = 'PulpUnit'
    Ream = 'Ream'
    Reel = 'Reel'
    Sheet = 'Sheet'
    ShortTon = 'ShortTon'
    Skid = 'Skid'
    SquareDecimeter = 'SquareDecimeter'
    SquareFoot = 'SquareFoot'
    SquareInch = 'SquareInch'
    SquareMeter = 'SquareMeter'
    ThousandPieces = 'ThousandPieces'
    ThousandSquareCentimeters = 'ThousandSquareCentimeters'
    ThousandSquareFeet = 'ThousandSquareFeet'
    ThousandSquareInches = 'ThousandSquareInches'
    Yard = 'Yard'


class Quantity(BaseModel):
    quantityContext: Optional[QuantityContext] = None
    quantityType: Optional[QuantityType] = None
    quantityUOM: Optional[QuantityUOM] = None
    quantityValue: Optional[float] = None


class OrderLineItem(BaseModel):
    changeable: Optional[bool] = None
    id: UUID
    orderLineItemNumber: confloat(ge=0.0)
    orderLineItemStatus: OrderLineItemStatus
    quantities: Optional[List[Quantity]] = None


class First(BaseModel):
    href: Optional[str] = None


class Last(BaseModel):
    href: Optional[str] = None


class Next(BaseModel):
    href: Optional[str] = None


class Prev(BaseModel):
    href: Optional[str] = None


class PaginationLinks(BaseModel):
    first: Optional[First] = None
    last: Optional[Last] = None
    next: Next
    prev: Optional[Prev] = None


class ListOfOrders(BaseModel):
    links: Optional[PaginationLinks] = None
    orders: Optional[List[OrderHeader]] = None


class Order(OrderHeader):
    links: Optional[PaginationLinks] = None
    orderLineItems: Optional[List[OrderLineItem]] = None


class GetOrder(RootModel[Order]):
    root: Order
